
////
This file is generated! See etc/fields.yml and scripts/generate_field_docs.py
////

[[exported-fields]]
= Exported Fields

[partintro]

--
This document describes the fields that are exported by Cloudtrailbeat. They are
grouped in the following categories:

* <<exported-fields-beat>>
* <<exported-fields-cloud>>
* <<exported-fields-cloudtrailbeat>>

--
[[exported-fields-beat]]
== Beat Fields

Contains common beat fields available in all event types.



[float]
=== beat.name

The name of the Beat sending the log messages. If the Beat name is set in the configuration file, then that value is used. If it is not set, the hostname is used. To set the Beat name, use the `name` option in the configuration file.


[float]
=== beat.hostname

The hostname as returned by the operating system on which the Beat is running.


[float]
=== beat.version

The version of the beat that generated this event.


[float]
=== @timestamp

type: date

example: August 26th 2016, 12:35:53.332

format: date

required: True

The timestamp when the event log record was generated.


[float]
=== tags

Arbitrary tags that can be set per Beat and per transaction type.


[float]
=== fields

type: dict

Contains user configurable fields.


[[exported-fields-cloud]]
== Cloud Provider Metadata Fields

Metadata from cloud providers added by the add_cloud_metadata processor.



[float]
=== meta.cloud.provider

example: ec2

Name of the cloud provider. Possible values are ec2, gce, or digitalocean.


[float]
=== meta.cloud.instance_id

Instance ID of the host machine.


[float]
=== meta.cloud.machine_type

example: t2.medium

Machine type of the host machine.


[float]
=== meta.cloud.availability_zone

example: us-east-1c

Availability zone in which this host is running.


[float]
=== meta.cloud.project_id

example: project-x

Name of the project in Google Cloud.


[float]
=== meta.cloud.region

Region in which this host is running.


[[exported-fields-cloudtrailbeat]]
== cloudtrailbeat Fields

None


[float]
== cloudtrail Fields

Contains CloudTrail access logs.


[float]
=== cloudtrail.eventTime

type: keyword

The date and time the request was made, in coordinated universal time (UTC).

[float]
=== cloudtrail.eventVersion

type: keyword

The version of the log event format. The current version is 1.02.

[float]
== userIdentity Fields

Information about the user that made a request. For more information, see CloudTrail userIdentity Element


[float]
=== cloudtrail.userIdentity.type

type: keyword

The request was made with your AWS account credentials.

[float]
=== cloudtrail.userIdentity.userName

type: keyword

The friendly name of the identity that made the call.

[float]
=== cloudtrail.userIdentity.principalId

type: keyword

A unique identifier for the entity that made the call.

[float]
=== cloudtrail.userIdentity.arn

type: keyword

The Amazon Resource Name (ARN) of the principal that made the call.

[float]
=== cloudtrail.userIdentity.accountId

type: keyword

The account that owns the entity that granted permissions for the request.

[float]
=== cloudtrail.userIdentity.accessKeyId

type: keyword

The access key ID that was used to sign the request.

[float]
== sessionContext Fields

If the request was made with temporary security credentials, an element that provides information about the session that was created for those credentials.



[float]
=== cloudtrail.userIdentity.sessionContext.attributes.creationDate

type: keyword

[float]
=== cloudtrail.userIdentity.sessionContext.attributes.mfaAuthenticated

type: keyword

[float]
=== cloudtrail.userIdentity.invokedBy

type: keyword

The name of the AWS service if that made the request, such as Auto Scaling or AWS Elastic Beanstalk.

[float]
=== cloudtrail.userIdentity.sessionIssuer

type: keyword

If the request was made with temporary security credentials, an element that provides information about how the credentials were obtained.

[float]
=== cloudtrail.userIdentity.webIdFederationData

type: keyword

If the request was made with temporary security credentials obtained by web identity federation, an element that lists information about the identity provider.

[float]
=== cloudtrail.eventSource

type: keyword

The service that the request was made to. This name is normally a short form of the service name without spaces plus .amazonaws.com. For example, the eventSource field lists a call to AWS CloudFormation as cloudformation.amazonaws.com, a call to Amazon EC2 as ec2.amazonaws.com, and a call to Amazon Simple Workflow Service as swf.amazonaws.com. One exception to this convention is CloudWatch, for which the event source is monitoring.amazonaws.com.

[float]
=== cloudtrail.eventName

type: keyword

The requested action, which is one of the actions listed in the API Reference for the service.

[float]
=== cloudtrail.awsRegion

type: keyword

The AWS region that the request was made to; for example, us-east-1.

[float]
=== cloudtrail.sourceIPAddress

type: keyword

The apparent IP address that the request was made from. For actions that originate from the service console, the address reported is for the underlying customer resource, not the console web server. For services in AWS, only the DNS name is displayed.

[float]
=== cloudtrail.errorCode

type: keyword

The AWS service error if the request returns an error.

[float]
=== cloudtrail.errorMessage

type: keyword

If the request returns an error, the description of the error. This message includes messages for authorization failures.

[float]
=== cloudtrail.requestParameters

type: keyword

The parameters, if any, that were sent with the request.

[float]
=== cloudtrail.responseElements

type: keyword

The response element for actions that make changes (create, update, or delete actions). If an action does not change state (for example, a request to get or list objects), this element is omitted.

[float]
=== cloudtrail.requestID

type: keyword

Value generated by the service being called that identifies the request.

[float]
=== cloudtrail.eventID

type: keyword

GUID generated by CloudTrail to uniquely identify each event. You can use this value to identify a single event. For example, you can use the ID as a primary key to retrieve log data from a searchable database.

[float]
=== cloudtrail.eventType

type: keyword

Identifies the type of event that generated the event record.

[float]
=== cloudtrail.apiVersion

type: keyword

Identifies the API version number associated with the AwsApiCall eventType value.

[float]
=== cloudtrail.recipientAccountID

type: keyword

Represents the account ID that received this event.

